# Copyright (c) 2021 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '07:00'
      timezone: 'America/Los_Angeles'
    labels:
      - 'dependencies'
    reviewers:
      - 'nerdondon'
