[package]
name = "raindb"
authors = ["nerdondon"]
description = "A persistent key-value store implemented based on an LSM tree implemented in Rust"
repository = "https://github.com/nerdondon/raindb"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]

[dev-dependencies]
pretty_assertions = "0.7.0"
