[package]
name = "http_server"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
log = "0.4"
raindb = { path = "../.." }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
